### ISSUE TITLE
ForceClose On Windows

### ISSUE THREAD

**Issue by najiha** [ndalu-id/baileys-api#3]
sepertinya berjalan dengan baik. namun secara iseng saya menemukan beberapa bug pada proses initiate jika saya jalankan di Windows node server tiba-tiba force close harus perintah start lagi. sepertinya ada di bagian delete token

**Comment by ndalu-id** [comment]
Isa ceritakan kasusnya?

**Comment by najiha** [comment]
saya baru menjelajahi sampai pada proses initiating credential baru, -> scan barcode -> whatsapp. Sampai sini berjalan baik. ketika saya logout dari smartphone maka nodejs->stopped. harus start lagi
ketika kita tidak initiating token, dan iseng klik delete token, ini juga menyebabkan nodejs-stopped. wajar sih bisa disiasati pada bagian frontend dengan disable tombol. tapi alangkah lebih bagus ada tambahan script pada bagian deleteCredential ->jika credential = 0 ->do nothing.

**Comment by ndalu-id** [comment]
Disaya kok tidak menemukan forceclose ya?
Di windows ataupun di linux?
Bisa coba screenshoot terminal saat forceclose?

**Comment by fitwan** [comment]
Iya, disaya juga terjadi seperti itu, waktu logout dari HP dan nodejs stop

**Comment by fitwan** [comment]
INFO [2022-08-04 03:38:24.347 +0700]: synced critical_block to v9
Connection closed. You are logged out.
(node:236659) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Try to connecting test
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored (conflict)
        at WebSocket.<anonymous> (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:414:13)
        at WebSocket.emit (node:events:526:28)
        at /www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:220:35
        at Object.decodeFrame (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)
        at WebSocket.onMessageRecieved (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:196:15)
        at WebSocket.emit (node:events:526:28)
        at Receiver.receiverOnMessage (/www/wwwroot/baileys-api-main/node_modules/ws/lib/websocket.js:1178:20)
        at Receiver.emit (node:events:526:28)
        at Receiver.dataMessage (/www/wwwroot/baileys-api-main/node_modules/ws/lib/receiver.js:513:14)
        at Receiver.getData (/www/wwwroot/baileys-api-main/node_modules/ws/lib/receiver.js:446:17) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-08-03T20:38:24.537Z
  }
}
credentials/test is deleted
ERROR [2022-08-04 03:38:24.535 +0700]: stream errored out
    node: {
      "tag": "stream:error",
      "attrs": {
        "code": "401"
      },
      "content": [
        {
          "tag": "conflict",
          "attrs": {
            "type": "device_removed"
          }
        }
      ]
    }
INFO [2022-08-04 03:38:24.536 +0700]: connection errored
    trace: "Error: Stream Errored (conflict)\n    at WebSocket.<anonymous> (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:414:13)\n    at WebSocket.emit (node:events:526:28)\n    at /www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:220:35\n    at Object.decodeFrame (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:196:15)\n    at WebSocket.emit (node:events:526:28)\n    at Receiver.receiverOnMessage (/www/wwwroot/baileys-api-main/node_modules/ws/lib/websocket.js:1178:20)\n    at Receiver.emit (node:events:526:28)\n    at Receiver.dataMessage (/www/wwwroot/baileys-api-main/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/www/wwwroot/baileys-api-main/node_modules/ws/lib/receiver.js:446:17)"
using Chrome v104.0.5112.79, isLatest: true
using WA v2.2228.8, isLatest: true
connection update {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
INFO [2022-08-04 03:38:26.849 +0700]: connected to WA Web
    browser: [
      "Linux",
      "Chrome",
      "103.0.5060.114"
    ]
    helloMsg: {
      "clientHello": {
        "ephemeral": "gFWCwkshy3gqxsA4VH+Gve/2wkP4qoLbIgu2qEhLZz0="
      }
    }
INFO [2022-08-04 03:38:27.065 +0700]: logging in...
    node: {
      "username": "6281289589922",
      "passive": true,
      "userAgent": {
        "platform": "WEB",
        "appVersion": {
          "primary": 2,
          "secondary": 2228,
          "tertiary": 8
        },
        "mcc": "000",
        "mnc": "000",
        "osVersion": "0.1",
        "manufacturer": "",
        "device": "Desktop",
        "osBuildNumber": "0.1",
        "releaseChannel": "RELEASE",
        "localeLanguageIso6391": "en",
        "localeCountryIso31661Alpha2": "US"
      },
      "webInfo": {
        "webSubPlatform": "WEB_BROWSER"
      },
      "connectType": "WIFI_UNKNOWN",
      "connectReason": "USER_ACTIVATED",
      "device": 68
    }
Connection closed. You are logged out.
Try to connecting test
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Connection Failure
        at WebSocket.<anonymous> (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:419:13)
        at WebSocket.emit (node:events:526:28)
        at /www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:220:35
        at Object.decodeFrame (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)
        at WebSocket.onMessageRecieved (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:196:15)
        at WebSocket.emit (node:events:526:28)
        at Receiver.receiverOnMessage (/www/wwwroot/baileys-api-main/node_modules/ws/lib/websocket.js:1178:20)
        at Receiver.emit (node:events:526:28)
        at Receiver.dataMessage (/www/wwwroot/baileys-api-main/node_modules/ws/lib/receiver.js:513:14)
        at Receiver.getData (/www/wwwroot/baileys-api-main/node_modules/ws/lib/receiver.js:446:17) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-08-03T20:38:29.039Z
  }
}
INFO [2022-08-04 03:38:29.039 +0700]: connection errored
    trace: "Error: Connection Failure\n    at WebSocket.<anonymous> (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:419:13)\n    at WebSocket.emit (node:events:526:28)\n    at /www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:220:35\n    at Object.decodeFrame (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/www/wwwroot/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:196:15)\n    at WebSocket.emit (node:events:526:28)\n    at Receiver.receiverOnMessage (/www/wwwroot/baileys-api-main/node_modules/ws/lib/websocket.js:1178:20)\n    at Receiver.emit (node:events:526:28)\n    at Receiver.dataMessage (/www/wwwroot/baileys-api-main/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/www/wwwroot/baileys-api-main/node_modules/ws/lib/receiver.js:446:17)"
/www/wwwroot/baileys-api-main/src/router/model/whatsapp.js:599
            throw err;
            ^

[Error: ENOENT: no such file or directory, stat 'credentials/test'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'credentials/test'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@wagateway:/www/wwwroot/baileys-api-main#

**Comment by ndalu-id** [comment]
check for the new update update / use pm2/nodemon
