### ISSUE TITLE
Error SCAN QR

### ISSUE THREAD

**Issue by CodingDisini** [ndalu-id/baileys-api#4]
Halo mas , di update yg sekarang saat melakukan SCAN QR terjadi error.

`INFO [2022-08-03 13:48:18.493 +0700]: pairing configured successfully, expect to restart the connection...
    me: {
      "id": "628988129401:7@s.whatsapp.net"
    }
    platform: "android"
ERROR [2022-08-03 13:48:18.768 +0700]: stream errored out
    node: {
      "tag": "stream:error",
      "attrs": {
        "code": "515"
      }
    }
INFO [2022-08-03 13:48:18.768 +0700]: connection errored
    trace: "Error: Stream Errored (restart required)\n    at WebSocket.<anonymous> (/Users/ardesign/Downloads/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:414:13)\n    at WebSocket.emit (node:events:394:28)\n    at /Users/ardesign/Downloads/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:220:35\n    at Object.decodeFrame (/Users/ardesign/Downloads/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/Users/ardesign/Downloads/baileys-api-main/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:196:15)\n    at WebSocket.emit (node:events:394:28)\n    at Receiver.receiverOnMessage (/Users/ardesign/Downloads/baileys-api-main/node_modules/ws/lib/websocket.js:1178:20)\n    at Receiver.emit (node:events:394:28)\n    at Receiver.dataMessage (/Users/ardesign/Downloads/baileys-api-main/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/Users/ardesign/Downloads/baileys-api-main/node_modules/ws/lib/receiver.js:446:17)"
> QRCODE v094p8hgtr1l IS READY
Interval check connection`

**Comment by ndalu-id** [comment]
Already updated.
Downgrade chrome version.
